# -*- mode: ruby -*-
# vi: set ft=ruby :

=begin
credits:   https://github.com/StefanScherer/docker-windows-box/blob/master/windows10/Vagrantfile

=end

Vagrant.configure("2") do |config|
    config.vm.box = "StefanScherer/windows_10"
  
    # Networking
    # config.vm.network "private_network", ip: "10.2.2.11"
    config.vm.network "forwarded_port", id: "rdp", guest: 3389, host: 3389,  autocorrect: true
    config.vm.network "forwarded_port", id: "ssh", guest: 22,   host: 10022, autocorrect: true
    config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
            
    config.vm.hostname = "win10"
    config.vm.communicator = "winrm"
  
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"
  
    config.vm.guest = :windows
    config.windows.halt_timeout = 15
  
    config.vm.provision "shell", path: "scripts/install-container-feature.ps1", privileged: true
    config.vm.provision "shell", path: "scripts/enable-autologon.ps1", privileged: true
    config.vm.provision "reload"
    config.vm.provision "shell", path: "scripts/add-docker-group.ps1", privileged: true
    config.vm.provision "shell", path: "scripts/install-docker.ps1", privileged: true
    config.vm.provision "shell", path: "scripts/install-chocolatey.ps1", privileged: false
    config.vm.provision "shell", path: "scripts/install-dockertools.ps1", privileged: false
    config.vm.provision "reload"
  
    ["vmware_fusion", "vmware_workstation"].each do |provider|
      config.vm.provider provider do |v, override|
        v.gui = true
        v.memory = 5096
        v.cpus = 2
      end
    end
  
    config.vm.provider "vmware_fusion" do |v|
      v.vmx["gui.fitguestusingnativedisplayresolution"] = "TRUE"
      v.vmx["mks.enable3d"] = "TRUE"
      v.vmx["mks.forceDiscreteGPU"] = "TRUE"
      v.vmx["gui.fullscreenatpoweron"] = "TRUE"
      v.vmx["gui.viewmodeatpoweron"] = "fullscreen"
      v.vmx["gui.lastPoweredViewMode"] = "fullscreen"
      v.vmx["sound.startconnected"] = "TRUE"
      v.vmx["sound.present"] = "TRUE"
      v.vmx["sound.autodetect"] = "TRUE"
      v.enable_vmrun_ip_lookup = false
      v.vmx["vhv.enable"] = "TRUE"
    end
  
    config.vm.provider "vcloud" do |v|
      v.memory = 4096
      v.cpus = 2
      v.nested_hypervisor = true
    end

	#
	# Global VirtualBox Options
	config.vm.provider "virtualbox" do |vb|
		vb.linked_clone = true
		vb.memory = 5120
		vb.gui = false
		vb.name = "Win10DevelopmentEnv"
		vb.customize ["modifyvm", :id, "--vram", "24"]
    end

  end