[build]
  publish = "public"
  command = "hugo --gc --minify --enableGitInfo --buildDrafts"

[context.production.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"
