# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
    config.vm.box = "bento/amazonlinux-2"
    config.vm.box_version = "1.0.0"

    config.vm.provision :shell, path: "scripts/bootstrap.sh"


    #
    # Global VirtualBox Options
    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.memory = 2048
        vb.gui = false
    end    
end