# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-18.04"
    config.vm.provision :shell, path: "scripts/bootstrap.sh"

    #
    # Global VirtualBox Options
    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
        vb.memory = 2048
        vb.gui = false
        # vb.name = "WinserverNetCoreDevelopmentEnvironment"
        vb.customize ["modifyvm", :id, "--vram", "256"]
    end
 
end